Repository wanted-preonboarding-TEAM2/JARANDA, pull requests merged in 2021-08, with the labels that each got.

#10 Feat/search component
  package.json
  src/App.js
  src/components/Admin/SearchBox.jsx
  src/components/Admin/SearchDropdown.jsx
  src/pages/Admin.jsx
  src/styles/reset.js
Labels: feature

#12 feat: dropdown 기능 구현 (#11)
  package-lock.json
  package.json
  src/components/Admin/SearchBox.jsx
  src/components/Admin/SearchDropdown.jsx
  yarn.lock
Labels: feature

#15 feat: 검색기능 구현 (#13)
  src/components/Admin/SearchBox.jsx
  src/components/Admin/SearchDropdown.jsx
  src/components/Admin/users.json
  src/constants/localStorageKey.js
  src/utils/localStorageHelper.js
Labels: feature

#18 refactor: 상수화 및 hook 생성
  src/components/Admin/SearchBox.jsx
  src/components/Admin/SearchDropdown.jsx
  src/constants/user.js
  src/utils/hooks/useDetectOutsideClick.js
Labels: refactor

#22 Feat/gnb UI
  public/favicon.ico
  public/images/jaranda_logo.png
  public/logo192.png
  public/logo512.png
  src/components/Layout/GNB/GNB.js
  src/components/Layout/GNB/MenuItem.js
  src/components/Layout/Layout.js
  src/constants/acceptedPageByRole.js
  src/constants/role.js
  src/pages/Admin.jsx
  src/routes/routes.js
  src/styles/reset.js
Labels: feature

#31 fix: searchDropBox UI 수정 (#28)
  src/components/Admin/SearchBox.jsx
  src/components/Admin/SearchDropdown.jsx
  src/pages/Admin.jsx
Labels: fix, styles

#34 Pagination 구현 완료
  src/components/Admin/PageButton.jsx
  src/components/Admin/PagedButtonList.jsx
  src/pages/Admin.jsx
Labels: feature, fix, refactor

#39 [fix] 페이지네이션 버그 해결 (#38)
  src/components/Admin/PagedButtonList.jsx
Labels: fix

#40 Feat/routing with auth
  package.json
  src/components/Layout/GNB/GNB.js
  src/constants/routesPath.js
  src/index.js
  src/pages/Forbidden.jsx
  src/pages/Parents.jsx
  src/pages/Teacher.jsx
  src/routes/AdminRoute.js
  src/routes/ParentRoute.js
  src/routes/RouteIf.js
  src/routes/TeacherRoute.js
  src/routes/routes.js
  src/services/redux/slices/user.js
  src/services/redux/store.js
  yarn.lock
Labels: feature

#45 searchBox 기능 구현
  .gitignore
  src/components/Admin/PagedButtonList.jsx
  src/components/Admin/SearchBox.jsx
  src/pages/Admin.jsx
Labels: feature

#51 Feat/admin add user
  src/components/signup/Form.js
  src/components/signup/index.js
  src/modal/Modal.js
  src/pages/Admin.jsx
  src/pages/Signup.jsx
Labels: feature

#59 fix: 페이지네이션 화살표 아이콘 버그 해결
  .gitignore
  package-lock.json
  src/components/Admin/PagedButtonList.jsx
  src/pages/Admin.jsx
Labels: fix

#63 Feat/close drop down click outside
  src/components/Dropdown/DropDown.jsx
Labels: feature

#69 feat: H1 추가 후 숨김 (#68)
  src/pages/Home.jsx
Labels: enhancement, feature

#73 feat: 입력하면서 검색하는 기능 (#32)
  src/components/Admin/PageButton.jsx
  src/components/Admin/SearchBox.jsx
Labels: feature

#76 Feat/search debouncing
  src/components/Admin/SearchBox.jsx
  src/pages/Admin.jsx
  src/services/utils/searchUsersByOption.js
  src/utils/hooks/useDebounce.js
Labels: feature

#81 fix: Signin Import 경로 수정 (#80)
  src/pages/index.jsx
Labels: fix

#85 Feat/adminpage add user
  src/components/Admin/SearchBox.jsx
  src/components/Admin/users.json
  src/components/Table/table.jsx
  src/components/signup/Form.js
  src/components/signup/index.js
  src/modal/CreditCardModal.js
  src/pages/Admin.jsx
  src/pages/Signup.jsx
Labels: fix

#93 Refactor/signup modal component
  src/constants/routesPath.js
  src/modal/SignupModal.js
  src/pages/Admin.jsx
  src/pages/ApplyTeacher.jsx
  src/pages/Help.jsx
  src/pages/index.jsx
Labels: refactor

#117 테이블 리팩토링 & json 데이터 수정
  src/components/Admin/users.json
  src/components/Table/table.jsx
  src/constants/role.js
  src/constants/user.js
Labels: fix

#130 Fix/route nomatch
  src/pages/RouteNoMatch/RouteNoMatch.jsx
Labels: bug, fix

#139 chore: 콘솔로그 및 주석 제거 (#138)
  src/components/Admin/Pagination.jsx
  src/components/Admin/SearchBox.jsx
  src/components/Layout/Layout.js
  src/components/Table/table.jsx
  src/pages/Admin/AccountManagement.jsx
  src/pages/SignUp/AddressInfo.js
  src/routes/RouteIf.js
  src/routes/TeacherRoute.js
Labels: chore
